version: "3"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - NODE_ENV=production
      - WAIT_HOSTS=redis:6379
    ports:
      - "3000:3000"

  redis:
    image: "redis"
    command: "redis-server"
